version: "3.4"
services:
  elasticsearch:
    restart: always
    container_name: elasticsearch
    build:
      context: .
      dockerfile: Dockerfile
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    ports:
      - "9200:9200" # elasticsearch json
      - "9300:9300" # elasticsearch transport interface
    volumes:
      - elastic-data:/var/lib/elasticsearch
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
      - "network.host=0.0.0.0"
      - "discovery.zen.minimum_master_nodes=1"
      - "discovery.type=single-node"
      - "AWS_SMTP_USER=${AWS_SMTP_USER}"
      - "AWS_SMTP_PASSWORD=${AWS_SMTP_PASSWORD}"
      - "AWS_SMTP_HOST=${AWS_SMTP_HOST}"
      - "AWS_SMTP_PORT=${AWS_SMTP_PORT}"
      - "HOSTNAME=${HOSTNAME}"
      - "ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD}"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk
    logging:
      options:
        max-size: "25M"
        max-file: "3"
  kibana:
    restart: always
    container_name: kibana
    depends_on:
      - elasticsearch
      - nginx
    image: docker.elastic.co/kibana/kibana:6.5.4
    networks:
      - elk
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      ELASTICSEARCH_PASSWORD: "${ELASTICSEARCH_PASSWORD}"
    volumes:
      - kibana-data:/usr/share/kibana/data
    logging:
      options:
        max-size: "25M"
        max-file: "3"
  logstash:
    ports:
      - "5044:5044"
    restart: always
    image: docker.elastic.co/logstash/logstash:6.6.0
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash.yml:/etc/logstash/logstash.yml
      - ./logstash-nginx-es.conf:/etc/logstash/conf.d/logstash-nignx-es.conf
networks:
  elk:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24
volumes:
    elastic-data:
    kibana-letsencrypt:
    kibana-data:
